version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - security
      - automated-pr
    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - security
      - automated-pr
    groups:
      pip-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - security
      - automated-pr
    groups:
      docker-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
